// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package admin

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strings"
	"time"

	"github.com/dukerupert/hiri/internal/domain"
	"github.com/dukerupert/hiri/internal/platform/audit"
)

func equipmentEventLabel(action string) string {
	switch action {
	case audit.AuditEquipmentCreated:
		return "Added to the register"
	case audit.AuditEquipmentUpdated:
		return "Details edited"
	case audit.AuditEquipmentSentToShop:
		return "Taken to the shop"
	case audit.AuditEquipmentReturnedToService:
		return "Back in service"
	case audit.AuditEquipmentRetired:
		return "Retired"
	}
	parts := strings.SplitN(action, ".", 2)
	if len(parts) == 2 {
		verb := strings.ReplaceAll(parts[1], "_", " ")
		return strings.ToUpper(verb[:1]) + verb[1:]
	}
	return action
}

func equipmentEventMarker(action string) string {
	switch action {
	case audit.AuditEquipmentRetired:
		return "bg-rr-red"
	case audit.AuditEquipmentSentToShop:
		return "bg-rr-amber"
	default:
		return "bg-rr-surface"
	}
}

// EquipmentActivity is the machine's history — added, edited, taken away, put
// back, retired.
//
// Edits are the entries that earn this: a serial corrected or an ownership
// flipped from loaner to customer-owned changes who pays for the next repair,
// and without the timeline there is nothing to attribute that to.
func EquipmentActivity(entries []domain.AuditEntry, loc *time.Location) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = ActivityTimeline(entries, equipmentEventLabel, equipmentEventMarker, loc).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
