// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package admin

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strings"
	"time"

	"github.com/dukerupert/hiri/internal/domain"
	"github.com/dukerupert/hiri/internal/platform/audit"
)

// orderEventLabel returns a human-readable title for an audit action that
// shows up on an order's activity feed. Covers order.*, shipment.*, the
// order-related email.* sends, and the QuickBooks invoice lifecycle.
//
// Email sends get "Emailed …" phrasing on purpose: the single most common
// question this timeline has to answer is what the customer was actually told.
func orderEventLabel(action string) string {
	switch action {
	case audit.AuditOrderCreated:
		return "Order placed"
	case audit.AuditOrderStatusChanged:
		return "Status changed"
	case audit.AuditOrderCancelled:
		return "Order cancelled"
	case audit.AuditOrderRefunded:
		return "Order refunded"
	case audit.AuditOrderFulfilled:
		return "Marked fulfilled"
	case audit.AuditOrderShipped:
		return "Marked shipped"
	case audit.AuditOrderDelivered:
		return "Marked delivered"
	case audit.AuditOrderFulfillmentReverted:
		return "Fulfillment reverted"
	case audit.AuditOrderShipmentReverted:
		return "Shipment reverted"
	case audit.AuditOrderReadyForPickup:
		return "Marked ready for pickup"
	case audit.AuditOrderPickedUp:
		return "Marked picked up"
	case audit.AuditOrderOutForDelivery:
		return "Out for local delivery"
	case audit.AuditOrderLineItemVariantChanged:
		return "Line item option changed"
	case audit.AuditOrderShippingMethodChanged:
		return "Shipping method changed"
	case audit.AuditOrderSwitchedToPickup:
		return "Switched to local pickup"
	case audit.AuditOrderInternalNoteUpdated:
		return "Internal note updated"
	case audit.AuditOrderMarkedPaid:
		return "Marked paid by staff"
	case audit.AuditOrderPaymentCaptured:
		return "Payment captured"
	case audit.AuditOrderPaymentInvoiced:
		return "Invoiced"
	case audit.AuditOrderPaymentPartiallyPaid:
		return "Partially paid"
	case audit.AuditOrderPaymentOverdue:
		return "Payment overdue"
	case audit.AuditShipmentLabelCreated:
		return "Shipping label bought"
	case audit.AuditShipmentLabelRefundRequested:
		return "Label refund requested"
	case audit.AuditShipmentLabelRefunded:
		return "Label refunded by carrier"
	case audit.AuditShipmentLabelRefundFailed:
		return "Label refund refused"
	case audit.AuditShipmentStatusUpdated:
		return "Tracking updated"
	case audit.AuditShipmentImported:
		return "Shipment imported"
	case audit.AuditQBInvoiceCreated:
		return "QuickBooks invoice created"
	case audit.AuditQBInvoiceEmailed:
		return "QuickBooks invoice emailed"
	case audit.AuditQBInvoiceVoided:
		return "QuickBooks invoice voided"
	case audit.AuditEmailOrderConfirmed:
		return "Emailed order confirmation"
	case audit.AuditEmailOrderShipped:
		return "Emailed tracking number"
	case audit.AuditEmailOrderReadyForPickup:
		return "Emailed ready for pickup"
	case audit.AuditEmailOrderOutForDelivery:
		return "Emailed out for delivery"
	case audit.AuditEmailRefundIssued:
		return "Emailed refund notice"
	case audit.AuditEmailOrderReminderSent:
		return "Emailed order reminder"
	}
	parts := strings.SplitN(action, ".", 2)
	if len(parts) == 2 {
		verb := strings.ReplaceAll(parts[1], "_", " ")
		return strings.ToUpper(verb[:1]) + verb[1:]
	}
	return action
}

// orderEventMarker colors the timeline dot. Forward progress is amber,
// anything that undid or refused something is rust, everything else neutral.
func orderEventMarker(action string) string {
	switch action {
	case audit.AuditOrderCancelled,
		audit.AuditOrderRefunded,
		audit.AuditOrderFulfillmentReverted,
		audit.AuditOrderShipmentReverted,
		audit.AuditOrderPaymentOverdue,
		audit.AuditShipmentLabelRefundFailed,
		audit.AuditQBInvoiceVoided:
		return "bg-rr-red"
	case audit.AuditOrderCreated,
		audit.AuditOrderFulfilled,
		audit.AuditOrderShipped,
		audit.AuditOrderDelivered,
		audit.AuditOrderPickedUp,
		audit.AuditOrderMarkedPaid,
		audit.AuditOrderPaymentCaptured,
		audit.AuditShipmentLabelCreated:
		return "bg-rr-amber"
	default:
		return "bg-rr-surface"
	}
}

// OrderActivity renders the order's history: every audit entry recorded
// against the order itself plus those recorded against its shipments, merged
// newest-first by the handler.
//
// Before this existed the audit log could only be filtered by resource *type*,
// so "who cancelled this order, and when" was unanswerable from the admin.
func OrderActivity(entries []domain.AuditEntry, loc *time.Location) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div><h2 class=\"text-sm font-semibold text-rr-heading\">Activity</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(entries) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p class=\"mt-2 text-sm text-rr-muted\">No activity recorded yet.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<ol role=\"list\" class=\"mt-4 border border-rr-border bg-rr-surface p-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for i, e := range entries {
				templ_7745c5c3_Err = timelineRow(e, orderEventLabel(e.Action), orderEventMarker(e.Action), i == len(entries)-1, loc).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</ol>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
