// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: magic_links.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMagicLinkToken = `-- name: CreateMagicLinkToken :one
INSERT INTO magic_link_tokens (id, customer_id, token_hash, expires_at, purpose)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, customer_id, token_hash, expires_at, used_at, created_at, purpose
`

type CreateMagicLinkTokenParams struct {
	ID         uuid.UUID `json:"id"`
	CustomerID uuid.UUID `json:"customer_id"`
	TokenHash  string    `json:"token_hash"`
	ExpiresAt  time.Time `json:"expires_at"`
	Purpose    string    `json:"purpose"`
}

func (q *Queries) CreateMagicLinkToken(ctx context.Context, arg CreateMagicLinkTokenParams) (MagicLinkToken, error) {
	row := q.db.QueryRow(ctx, createMagicLinkToken,
		arg.ID,
		arg.CustomerID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Purpose,
	)
	var i MagicLinkToken
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.Purpose,
	)
	return i, err
}

const deleteExpiredMagicLinkTokens = `-- name: DeleteExpiredMagicLinkTokens :exec
DELETE FROM magic_link_tokens
WHERE expires_at < now() OR used_at IS NOT NULL
`

func (q *Queries) DeleteExpiredMagicLinkTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredMagicLinkTokens)
	return err
}

const getValidMagicLinkToken = `-- name: GetValidMagicLinkToken :one
SELECT id, customer_id, token_hash, expires_at, used_at, created_at, purpose FROM magic_link_tokens
WHERE token_hash = $1 AND purpose = $2 AND used_at IS NULL AND expires_at > now()
`

type GetValidMagicLinkTokenParams struct {
	TokenHash string `json:"token_hash"`
	Purpose   string `json:"purpose"`
}

func (q *Queries) GetValidMagicLinkToken(ctx context.Context, arg GetValidMagicLinkTokenParams) (MagicLinkToken, error) {
	row := q.db.QueryRow(ctx, getValidMagicLinkToken, arg.TokenHash, arg.Purpose)
	var i MagicLinkToken
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.Purpose,
	)
	return i, err
}

const redeemMagicLinkToken = `-- name: RedeemMagicLinkToken :one
UPDATE magic_link_tokens
SET used_at = now()
WHERE token_hash = $1 AND purpose = $2 AND used_at IS NULL AND expires_at > now()
RETURNING id, customer_id, token_hash, expires_at, used_at, created_at, purpose
`

type RedeemMagicLinkTokenParams struct {
	TokenHash string `json:"token_hash"`
	Purpose   string `json:"purpose"`
}

func (q *Queries) RedeemMagicLinkToken(ctx context.Context, arg RedeemMagicLinkTokenParams) (MagicLinkToken, error) {
	row := q.db.QueryRow(ctx, redeemMagicLinkToken, arg.TokenHash, arg.Purpose)
	var i MagicLinkToken
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.Purpose,
	)
	return i, err
}
