// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error)
	CreateResetToken(ctx context.Context, arg CreateResetTokenParams) (ResetToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteAddress(ctx context.Context, arg DeleteAddressParams) error
	DeleteCustomer(ctx context.Context, id uuid.UUID) error
	GetAddress(ctx context.Context, arg GetAddressParams) (Address, error)
	GetAddressByID(ctx context.Context, id uuid.UUID) (Address, error)
	GetCustomerByEmail(ctx context.Context, email string) (Customer, error)
	GetCustomerByID(ctx context.Context, id uuid.UUID) (Customer, error)
	GetEmailVerificationByTokenHash(ctx context.Context, tokenHash string) (EmailVerification, error)
	GetResetTokenByTokenHash(ctx context.Context, tokenHash string) (ResetToken, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	ListAddresses(ctx context.Context, customerID *uuid.UUID) ([]Address, error)
	ListCustomers(ctx context.Context) ([]Customer, error)
	MarkEmailVerified(ctx context.Context, id uuid.UUID) error
	MarkResetTokenUsed(ctx context.Context, id uuid.UUID) error
	PruneExpiredSessions(ctx context.Context) (int64, error)
	RevokeAllSessionsForActor(ctx context.Context, arg RevokeAllSessionsForActorParams) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	UpdateCustomerEmail(ctx context.Context, arg UpdateCustomerEmailParams) (Customer, error)
	UpdateCustomerEmailVerified(ctx context.Context, arg UpdateCustomerEmailVerifiedParams) error
	UpdateCustomerGroup(ctx context.Context, arg UpdateCustomerGroupParams) error
	UpdateCustomerPassword(ctx context.Context, arg UpdateCustomerPasswordParams) error
	UpdateCustomerTaxExempt(ctx context.Context, arg UpdateCustomerTaxExemptParams) error
	UpdateSessionLastSeen(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
